tap "github/gh"
tap "homebrew-ffmpeg/ffmpeg"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "nbrown/nbrown-tap"
tap "universal-ctags/universal-ctags"
brew "ack"
brew "acpica"
brew "autoconf"
brew "automake"
brew "bat"
brew "icu4c"
brew "node"
brew "bitwarden-cli"
brew "brew-cask-completion"
brew "fontconfig"
brew "xz"
brew "python@3.9"
brew "glib"
brew "capstone"
brew "carthage"
brew "ccache"
brew "ccat"
brew "chezmoi"
brew "cmake"
brew "cmake-docs"
brew "coreutils"
brew "cpanminus"
brew "cscope"
brew "discount"
brew "dockutil"
brew "emojify"
brew "exa"
brew "fasd"
brew "fd"
brew "fzf"
brew "isl"
brew "gcc"
brew "gh"
brew "git-delta"
brew "git-extras"
brew "gnu-getopt"
brew "gnu-sed"
brew "libtool"
brew "gnupg"
brew "lua"
brew "go"
brew "gperf"
brew "graphviz"
brew "python@3.10"
brew "grc"
brew "hub"
brew "shared-mime-info"
brew "python@3.8"
brew "imagemagick"
brew "jq"
brew "launchctl-completion"
brew "pcre2"
brew "less"
brew "libmagic"
brew "ruby"
brew "macvim"
brew "make"
brew "mas"
brew "neovim"
brew "openssl@3"
brew "pstree"
brew "pygments"
brew "qemu"
brew "ripgrep"
brew "rlwrap"
brew "shellcheck"
brew "shfmt"
brew "speedtest-cli"
brew "subversion"
brew "tag"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "yara"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-lovers"
brew "zsh-syntax-highlighting"
brew "zsh-you-should-use"
brew "zshdb"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "adoptopenjdk"
cask "alfred"
cask "beyond-compare"
cask "brewservicesmenubar"
cask "diffmerge"
cask "docker"
cask "font-anonymice-powerline"
cask "font-consolas-for-powerline"
cask "font-dejavu-sans-mono-for-powerline"
cask "font-droid-sans-mono-for-powerline"
cask "font-fira-mono-for-powerline"
cask "font-inconsolata-dz-for-powerline"
cask "font-inconsolata-for-powerline"
cask "font-inconsolata-g-for-powerline"
cask "font-liberation-mono-for-powerline"
cask "font-menlo-for-powerline"
cask "font-meslo-for-powerline"
cask "font-meslolg-nerd-font"
cask "font-monofur-for-powerline"
cask "font-roboto-mono-for-powerline"
cask "font-source-code-pro-for-powerline"
cask "font-ubuntu-mono-derivative-powerline"
cask "ghidra"
cask "hyper"
cask "iterm2"
cask "keybase"
cask "kitematic"
cask "kitty"
cask "meld"
cask "miniconda"
cask "steam"
cask "suspicious-package"
cask "temurin"
cask "unicodechecker"
cask "vagrant"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "xquartz"
mas "Bitwarden", id: 1352778147
mas "Duplicate File Finder", id: 1032755628
mas "Evernote", id: 406056744
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Lingo", id: 624884154
mas "Logic Problems", id: 879060318
mas "Microsoft OneNote", id: 784801555
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Radiant Defense", id: 512204619
mas "Spike", id: 707452888
mas "The Sandbox", id: 688254765
mas "The Unarchiver", id: 425424353
mas "Tower Defense", id: 580767020
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
